spring:
  datasource:
    url: jdbc:mysql://125.191.212.64:3307/community_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ahndy84
    password: samsung10!
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
server:
  port: 8081