spring:
  datasource:
    url: jdbc:mysql://125.191.212.64:3307/community_test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ahndy84
    password: samsung10!
    driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#    serialization:
#      fail-on-empty-beans: false #빈값은 직렬화하지 않음
server:
  port: 8081